name: Master Eva Feed Update

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_master_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests lxml

      - name: Run Master Eva Script
        run: python masterevaxml.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Вказуємо папку, де лежить файл. . - це корінь
          path: .
          # Ми завантажуємо тільки Masterevanew.xml, щоб не вантажити зайвого
          pattern: Masterevanew.xml

  deploy:
    needs: build_master_feed
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
